// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AppliedFSharpConsole")>]
[<assembly: AssemblyProductAttribute("AppliedFSharp")>]
[<assembly: AssemblyDescriptionAttribute("My submission for the F# Applied Challenge")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AppliedFSharpConsole"
    let [<Literal>] AssemblyProduct = "AppliedFSharp"
    let [<Literal>] AssemblyDescription = "My submission for the F# Applied Challenge"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
